"""followers

Revision ID: 587165b82d38
Revises: ffdb25c20c2a
Create Date: 2019-07-13 22:06:20.375743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587165b82d38'
down_revision = 'ffdb25c20c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
